"""
course_utils.py — small helpers shared by the course notebooks.

Everything in here is deliberately simple and readable: the goal is to keep
the notebooks focused on the *ideas*, not on boilerplate.  Feel free to open
this file and read it; nothing is hidden.

Contents
--------
set_style()               consistent, colour-blind-friendly matplotlib style
PALETTE                   the categorical colours used throughout the course
plot_decision_boundary()  2-D decision regions of a fitted classifier
load_*()                  dataset loaders (bundled CSVs, classic datasets, and
                          online datasets with an offline fallback)
"""
from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
RANDOM_STATE = 42

# A categorical palette that stays distinguishable for the common forms of
# colour-vision deficiency (validated for adjacent-pair separation).
PALETTE = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]


def set_style() -> None:
    """Apply the course-wide plotting style (colour-blind-safe palette, light grid, no chart junk)."""
    mpl.rcParams.update({
        "figure.figsize": (7.5, 4.5),
        "figure.dpi": 100,
        "axes.prop_cycle": mpl.cycler(color=PALETTE),
        "axes.grid": True,
        "grid.alpha": 0.3,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 12,
        "axes.titleweight": "semibold",
        "axes.labelsize": 10.5,
        "legend.frameon": False,
        "lines.linewidth": 2,
        "image.cmap": "viridis",
        "savefig.bbox": "tight",
    })


def plot_decision_boundary(model, X, y, ax=None, resolution: int = 300, alpha: float = 0.25,
                           title: str | None = None, feature_names=("feature 1", "feature 2"),
                           proba: bool = False, legend: bool = True):
    """Draw the decision regions of a fitted 2-D classifier together with the data.

    Parameters
    ----------
    model : fitted estimator with ``predict`` (and ``predict_proba`` if proba=True)
    X : array of shape (n_samples, 2)
    y : array of class labels
    proba : if True and the classifier is binary, shade P(y=1) instead of the hard prediction
    legend : set to False in panel grids where one shared legend is enough
    """
    X = np.asarray(X)
    y = np.asarray(y)
    if ax is None:
        _, ax = plt.subplots()
    x_min, x_max = X[:, 0].min(), X[:, 0].max()
    y_min, y_max = X[:, 1].min(), X[:, 1].max()
    pad_x, pad_y = 0.08 * (x_max - x_min + 1e-9), 0.08 * (y_max - y_min + 1e-9)
    xx, yy = np.meshgrid(np.linspace(x_min - pad_x, x_max + pad_x, resolution),
                         np.linspace(y_min - pad_y, y_max + pad_y, resolution))
    grid = np.c_[xx.ravel(), yy.ravel()]
    classes = np.unique(y)
    cmap = ListedColormap(PALETTE[: max(len(classes), 2)])
    if proba and len(classes) == 2:
        zz = model.predict_proba(grid)[:, 1].reshape(xx.shape)
        cs = ax.contourf(xx, yy, zz, levels=np.linspace(0, 1, 11), cmap="RdBu_r", alpha=0.6)
        plt.colorbar(cs, ax=ax, label="P(y = 1)")
        ax.contour(xx, yy, zz, levels=[0.5], colors="k", linewidths=1.2)
    else:
        zz = model.predict(grid)
        # map labels to 0..k-1 for colouring
        lookup = {c: i for i, c in enumerate(classes)}
        zz = np.vectorize(lookup.get)(zz).reshape(xx.shape)
        ax.contourf(xx, yy, zz, levels=np.arange(-0.5, len(classes) + 0.5, 1), cmap=cmap, alpha=alpha)
    for i, c in enumerate(classes):
        m = y == c
        ax.scatter(X[m, 0], X[m, 1], s=22, color=PALETTE[i % len(PALETTE)], edgecolor="white",
                   linewidth=0.5, label=f"class {c}")
    ax.set_xlabel(feature_names[0])
    ax.set_ylabel(feature_names[1])
    ax.grid(False)
    if title:
        ax.set_title(title)
    if legend:
        ax.legend(loc="best")
    return ax


# ---------------------------------------------------------------------------
# Bundled datasets (generated by ../data/make_datasets.py)
# ---------------------------------------------------------------------------
def load_churn(raw: bool = False) -> pd.DataFrame:
    """Synthetic telco-style customer churn data (5 005 rows incl. duplicates).

    ``raw=True`` returns the file exactly as shipped (with missing values, duplicated rows,
    inconsistent capitalisation and a few outliers) so that it can be cleaned in the course.
    ``raw=False`` applies the cleaning steps developed in notebook 04.
    """
    df = pd.read_csv(DATA_DIR / "customer_churn.csv", parse_dates=["signup_date"])
    if raw:
        return df
    df = df.drop_duplicates(subset="customer_id").copy()
    df["region"] = df["region"].str.title()
    df.loc[df["monthly_charges"] > 200, "monthly_charges"] = np.nan
    return df.reset_index(drop=True)


def load_energy_demand() -> pd.DataFrame:
    """Synthetic hourly electricity demand (2 years) with temperature and holiday flag."""
    return pd.read_csv(DATA_DIR / "energy_demand.csv", parse_dates=["timestamp"])


def load_loans() -> pd.DataFrame:
    """Synthetic loan applications with a documented historical bias (see notebook 19)."""
    return pd.read_csv(DATA_DIR / "loan_applications.csv")


def load_reviews() -> pd.DataFrame:
    """Small synthetic product-review corpus with sentiment labels (notebook 15)."""
    return pd.read_csv(DATA_DIR / "reviews.csv")


_AIR_PASSENGERS = [
    112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118,
    115, 126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140,
    145, 150, 178, 163, 172, 178, 199, 199, 184, 162, 146, 166,
    171, 180, 193, 181, 183, 218, 230, 242, 209, 191, 172, 194,
    196, 196, 236, 235, 229, 243, 264, 272, 237, 211, 180, 201,
    204, 188, 235, 227, 234, 264, 302, 293, 259, 229, 203, 229,
    242, 233, 267, 269, 270, 315, 364, 347, 312, 274, 237, 278,
    284, 277, 317, 313, 318, 374, 413, 405, 355, 306, 271, 306,
    315, 301, 356, 348, 355, 422, 465, 467, 404, 347, 305, 336,
    340, 318, 362, 348, 363, 435, 491, 505, 404, 359, 310, 337,
    360, 342, 406, 396, 420, 472, 548, 559, 463, 407, 362, 405,
    417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390, 432,
]


def load_air_passengers() -> pd.Series:
    """The classic Box & Jenkins 'airline passengers' series (monthly totals, 1949–1960, in thousands)."""
    idx = pd.date_range("1949-01-01", periods=len(_AIR_PASSENGERS), freq="MS")
    return pd.Series(_AIR_PASSENGERS, index=idx, name="passengers")


# ---------------------------------------------------------------------------
# Online datasets with offline fallbacks
# ---------------------------------------------------------------------------
def _notice(msg: str) -> None:
    print(f"[course_utils] {msg}")


def load_california_housing(as_frame: bool = True):
    """California housing (Pace & Barry, 1997) via scikit-learn; synthetic stand-in when offline."""
    try:
        from sklearn.datasets import fetch_california_housing
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            data = fetch_california_housing(as_frame=as_frame)
        return data
    except Exception as exc:  # no internet, blocked download, ...
        _notice(f"could not download California housing ({type(exc).__name__}); using a synthetic stand-in "
                "with the same columns. Results will differ from the real data.")
        rng = np.random.default_rng(RANDOM_STATE)
        n = 20640
        med_inc = np.clip(rng.lognormal(1.2, 0.5, n), 0.5, 15)
        house_age = rng.integers(1, 52, n).astype(float)
        ave_rooms = np.clip(rng.normal(5.4, 1.2, n), 1, 15)
        ave_bedrms = np.clip(ave_rooms * rng.normal(0.2, 0.03, n), 0.5, 5)
        population = np.clip(rng.lognormal(7.0, 0.8, n), 3, 30000)
        ave_occup = np.clip(rng.normal(3.0, 0.8, n), 1, 12)
        latitude = rng.uniform(32.5, 42.0, n)
        longitude = rng.uniform(-124.3, -114.3, n)
        coast = np.exp(-((longitude + 118.5) ** 2 + (latitude - 34.0) ** 2) / 6) + np.exp(-((longitude + 122.4) ** 2 + (latitude - 37.8) ** 2) / 3)
        price = (0.4 + 0.55 * med_inc - 0.015 * house_age + 0.05 * ave_rooms - 0.12 * ave_occup + 2.2 * coast
                 + rng.normal(0, 0.45, n))
        price = np.clip(price, 0.15, 5.0)
        frame = pd.DataFrame({"MedInc": med_inc, "HouseAge": house_age, "AveRooms": ave_rooms, "AveBedrms": ave_bedrms,
                              "Population": population, "AveOccup": ave_occup, "Latitude": latitude,
                              "Longitude": longitude})
        target = pd.Series(price, name="MedHouseVal")

        class _Bunch(dict):
            def __getattr__(self, k):
                return self[k]
        return _Bunch(data=frame if as_frame else frame.values, target=target if as_frame else target.values,
                      frame=pd.concat([frame, target], axis=1), feature_names=list(frame.columns),
                      target_names=["MedHouseVal"], DESCR="synthetic stand-in for the California housing data")


def load_penguins() -> pd.DataFrame:
    """Palmer penguins (Horst, Hill & Gorman, 2020) via seaborn; synthetic stand-in when offline."""
    try:
        import seaborn as sns
        return sns.load_dataset("penguins")
    except Exception as exc:
        _notice(f"could not download the penguins data ({type(exc).__name__}); using a synthetic stand-in.")
        rng = np.random.default_rng(RANDOM_STATE)
        specs = {  # species: (bill_length, bill_depth, flipper_length, body_mass, islands)
            "Adelie": ((38.8, 2.7), (18.3, 1.2), (190, 6.5), (3700, 460), ["Torgersen", "Biscoe", "Dream"]),
            "Chinstrap": ((48.8, 3.3), (18.4, 1.1), (196, 7.1), (3730, 380), ["Dream"]),
            "Gentoo": ((47.5, 3.1), (15.0, 1.0), (217, 6.5), (5080, 500), ["Biscoe"]),
        }
        rows = []
        for species, n in (("Adelie", 152), ("Chinstrap", 68), ("Gentoo", 124)):
            bl, bd, fl, bm, islands = specs[species]
            sex = rng.choice(["Male", "Female"], n)
            shift = np.where(sex == "Male", 1.0, -1.0)
            rows.append(pd.DataFrame({
                "species": species,
                "island": rng.choice(islands, n),
                "bill_length_mm": rng.normal(bl[0], bl[1], n) + 1.5 * shift,
                "bill_depth_mm": rng.normal(bd[0], bd[1], n) + 0.6 * shift,
                "flipper_length_mm": rng.normal(fl[0], fl[1], n) + 3 * shift,
                "body_mass_g": rng.normal(bm[0], bm[1], n) + 250 * shift,
                "sex": sex,
            }))
        df = pd.concat(rows, ignore_index=True).sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)
        for col in ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]:
            df[col] = df[col].round(1)
            df.loc[rng.random(len(df)) < 0.01, col] = np.nan
        df.loc[rng.random(len(df)) < 0.03, "sex"] = None
        return df


def load_adult() -> pd.DataFrame:
    """The 'Adult' census income data (Kohavi, 1996) via OpenML; falls back to the bundled loan data."""
    try:
        from sklearn.datasets import fetch_openml
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            adult = fetch_openml("adult", version=2, as_frame=True)
        df = adult.frame.copy()
        df["income"] = (df["class"].astype(str).str.contains(">50K")).astype(int)
        return df.drop(columns=["class"])
    except Exception as exc:
        _notice(f"could not download the Adult data ({type(exc).__name__}); use load_loans() instead "
                "(bundled, with a documented bias mechanism).")
        return load_loans()


def load_newsgroups(categories=("sci.space", "rec.sport.hockey", "talk.politics.misc", "comp.graphics")):
    """A 4-category subset of 20 Newsgroups (Lang, 1995); falls back to the bundled review corpus."""
    try:
        from sklearn.datasets import fetch_20newsgroups
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            data = fetch_20newsgroups(subset="all", categories=list(categories),
                                      remove=("headers", "footers", "quotes"), random_state=RANDOM_STATE)
        return pd.DataFrame({"text": data.data, "label": [data.target_names[t] for t in data.target]})
    except Exception as exc:
        _notice(f"could not download 20 Newsgroups ({type(exc).__name__}); using the bundled synthetic review corpus.")
        df = load_reviews()
        return pd.DataFrame({"text": df["text"], "label": df["product"]})


__all__ = ["PALETTE", "RANDOM_STATE", "set_style", "plot_decision_boundary", "load_churn", "load_energy_demand",
           "load_loans", "load_reviews", "load_air_passengers", "load_california_housing", "load_penguins",
           "load_adult", "load_newsgroups"]
